### ISSUE TITLE
No module named 'surface_utilities'

### ISSUE THREAD

**Issue by vedmathai** [kristianeschenburg/ddCRP#1]
In ddCRP/statistics.py there is an import from surface_utilities. But there doesn't seem to be a surface_utilities module. It is throwing an error when running the code. I looked through the code and couldn't find or its subfunctions that are being called, is there something I am missing?

**Comment by kristianeschenburg** [comment]
Hi @vedmathai sorry for the delay -- yes, surface_utilities is a package that I've been using that wasn't actually meant to be distributed -- I'll update the ddCRP code to include the necessary methods from surface_utilities.

**Comment by qihongl** [comment]
Is `surface_utilities` gonna be added recently? :)

**Comment by kristianeschenburg** [comment]
Hi @qihongl  and @vedmathai -- I've added a file called **adjacency.py** to the package, from which you can compute an an adjacency list, along with a boundary map.  **adjacency.py** include two classes: **SurfaceAdjacency** and **BoundaryMap**, which are now imported in the **statistics.py** file.
