### ISSUE TITLE
NameError: name 'np' is not defined

### ISSUE THREAD

**Issue by jinxmirror13** [kristianeschenburg/ddCRP#3]
Love that this is a tool that seems super easy to implement! I have been trying to build something like this on my own and was excited to find your tool... However I ran into some issues when installing it as requested...

I ran the installation instructions, `pip` installing it locally, but when running the Demo.ipynb on my own Jupyter Notebook system with the latest of each library (i already have `numpy`) it said: 

```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-1-1234567890> in <module>
      4 
      5 crp = ddCRP.ddCRP(alpha, model=niw, mcmc_passes=15, stats_interval=125)
----> 6 crp.fit(synth.features_, synth.adj_list_)

~/blahblahblah/ddCRP/ddCRP/ddCRP.py in fit(self, features, adj_list, init_z, init_c, gt_z, edge_prior)
    196 
    197                 deltaC = statistics.delta_C(parcels, parcels_new)
--> 198                 boundC = statistics.boundaries(z_new, adj_list)
    199                 K, z, parcels = K_new, z_new, parcels_new
    200                 steps += 1

~/blahblahblah/ddCRP/ddCRP/statistics.py in boundaries(label, adj_list, normed)
     78 
     79     bmap = BoundaryMap(label, adj_list)
---> 80     bmap.find_boundaries()
     81     boundC = bmap.boundaries.sum()
     82 

~/blahblahblah/ddCRP/ddCRP/adjacency.py in find_boundaries(self)
    147         label = self.label
    148 
--> 149         boundaries = np.zeros((label.shape))
    150 
    151         for i, k in enumerate(adj_list.keys()):

NameError: name 'np' is not defined
```
Running it on my Macbook Pro.

I think it is similar to this: [https://github.com/forrestbao/pyeeg/issues/14](https://github.com/forrestbao/pyeeg/issues/14)

**Comment by kristianeschenburg** [comment]
Thanks @jinxmirror13, I'll have a look at the notebook and code to see what's going on.

**Comment by kristianeschenburg** [comment]
Hi @jinxmirror13 -- I've fixed this issue, and the Demo.ipynb should work properly now.  I had written some auxilliary classes to process the adjacency lists, and did not include those with the package previously.

I've created a new file called "mesh_utilities.py" with two functions: ```unweightedadjacency```, that can be used to generate an adjacency matrix or list of your data, and ```find_boundaries``` that will identify vertices that share a boundary with a class that is of a different class than itself.

Please let me know if you come across any other issues.
