### ISSUE TITLE
Using custom data

### ISSUE THREAD

**Issue by Andrei997** [kristianeschenburg/ddCRP#4]
Hi, first of all I would like to thank you for sharing this package, it is much appreciated.

I am however a bit confused on how I would use it with my own data -> I would like to cluster sentence vectors [128 dim] based on their cosine-similarity. 

I have read the original paper but I would like to know what functions I need to implement [and where] to use this package for clustering sentence vectors. 
Thanks in advance!

**Comment by kristianeschenburg** [comment]
Hi @Andrei997 thanks for your interest in this package.  I'll note that all original credit goes to https://github.com/cbaldassano/Parcellating-connectivity (@cbaldassano) for his original implementation -- I just made most of the tools object-oriented and added some additional tools that I was interested in.

This tool is primarily dedicated to data whose domain is a Euclidean surface mesh, so you'll need to supply some sort of adjacency structure (dictionary of lists), in addition to the word feature vectors -- both of these are suppled to the ddCRP.fit() method.

Have a look at the Demo.ipynb notebook for one example.

**Comment by Andrei997** [comment]
Thank you for your reply! This seems like a good start so I will close this issue!
